name: Minitask Auth Flow 
run-name:  ${{github.event.head_commit.message}}
on:
    push:
        tags:
           - "v*"
permissions: 
    contents: write
    packages: write
jobs:
    release-app:
        name: "Release build"
        runs-on: ubuntu-latest
        steps:
            - name: get source
              uses: actions/checkout@v4
            - name: setup golang
              uses: actions/setup-go@v6
              with:
                go-version-file: go.mod
            - name: install go dependencies
              run: go mod tidy
            - name: build app in linux
              run: go build -o auth-linux-x64 main.go
            - name: build app windows
              run: GOOS=windows GOARCH=amd64 go build -o auth-windows.exe main.go
            - name: build app macOS
              run: GOOS=darwin GOARCH=arm64 go build -o auth-darwin-arm64 main.go
            - name: release
              uses: softprops/action-gh-release@v3
              with:
                files: |
                  auth-linux-x64
                  auth-windows.exe
                  auth-darwin-arm64

    build-docker-image:
        name: "Build app minitask"
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: login to docker
              run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin

            - name: build docker image
              run: docker build . -t ghcr.io/${{github.repository}}/minitask-authentication:latest 
            - name: push to ghcr.io
              run: docker push ghcr.io/${{github.repository}}/minitask-authentication:latest 
            